In [19]:
from sklearn import preprocessing
import numpy as np
X= [[-1,-1,2],
   [2,0,0],
    [0,1,-1],
   [-100,4,1]]
binarizer = preprocessing.Binarizer().fit(X)
print (binarizer.transform(X))

[[0 0 1]
 [1 0 0]
 [0 1 0]
 [0 1 1]]


In [26]:
binarizer = preprocessing.Binarizer(1.1)
print (binarizer.transform(X))

[[0 0 1]
 [1 0 0]
 [0 0 0]
 [0 1 0]]
