In [14]:
import numpy as np
from sklearn import preprocessing
X=np.asanyarray([[100,1.7,1],
            [80,1.9,0],
            [67,2.0,0]], dtype=np.float)
print X

[[ 100.     1.7    1. ]
 [  80.     1.9    0. ]
 [  67.     2.     0. ]]


In [15]:
X_normalizada = preprocessing.normalize(X, norm='l2')
print X_normalizada

[[ 0.99980556  0.01699669  0.00999806]
 [ 0.99971809  0.0237433   0.        ]
 [ 0.99955476  0.02983746  0.        ]]


In [16]:
X_cuadrada = X_normalizada**2
print X_cuadrada

[[  9.99611151e-01   2.88887623e-04   9.99611151e-05]
 [  9.99436255e-01   5.63744513e-04   0.00000000e+00]
 [  9.99109726e-01   8.90273759e-04   0.00000000e+00]]


In [17]:
X_suma_cuadrado = np.sum(X_cuadrada, axis=1)
print X_suma_cuadrado

[ 1.  1.  1.]
